# Simple Matrix to Clojure interaction

This shows how to put data in a matrix and out

In [1]:
(require '[opencv4.core :refer :all])

In [14]:
; we start by creating a 3x3 mat, where each pixel value 
; is made of 1 channel, so CV_8UC1.
(def mat (new-mat 3 3 CV_8UC1 (new-scalar 0.0)))

#'user/mat

In [15]:
; let's see what the inside of the mat looks like with dump
; dump just prints out the content, 
; and returns nil

(dump mat)

[0 0 0]
[0 0 0]
[0 0 0]


In [16]:
; we can retrieve the content as byte array using << on the mat
(<< mat)

#object["[B" 0x142901f5 "[B@142901f5"]

In [17]:
; it's hard to read what the byte array is, 
; so in clojure we can make a sequence out of it.
(seq (<< mat))

(0 0 0 0 0 0 0 0 0)

In [18]:
; let's replace the value in the mat, 
; by using the function >>, 
; that puts values inside the mat 
; using a byte array, here created from a range.
(>> mat (byte-array (range 9)))

#object[org.opencv.core.Mat 0xccd0f03 "Mat [ 3*3*CV_8UC1, isCont=true, isSubmat=false, nativeObj=0x7feaa28630e0, dataAddr=0x7feaa2863140 ]"]

In [19]:
; we can check the values again using seq and <<
(seq (<< mat))

(0 1 2 3 4 5 6 7 8)

In [20]:
; to multiply the content of the mat, 
; you can use, multiply! and a scalar.
(multiply! mat (new-scalar 2.0))

#object[org.opencv.core.Mat 0xccd0f03 "Mat [ 3*3*CV_8UC1, isCont=true, isSubmat=false, nativeObj=0x7feaa28630e0, dataAddr=0x7feaa2863140 ]"]

In [21]:
; we can check the values again using seq and <<, 
; and see that each value of the mat, 
; has been multiplied by 2
(seq (<< mat))

(0 2 4 6 8 10 12 14 16)