# intro on interaction between opencv mat object and clojure 

In [37]:
(require '[opencv4.core :refer :all])

we start by creating a 3x3 mat, where each pixel value is made of 1 channel, so the pixel type is CV_8UC1, for unsigned 8 bits, 1 channel.

In [38]:
(def mat (new-mat 3 3 CV_8UC1))

#'user/mat

let's see what the inside of the mat looks like with dump, dump is a function that prints out the content, and returns nil

In [39]:
(dump mat)

[0 0 0]
[0 0 0]
[0 0 0]


we can retrieve the content as byte array using << on the mat

In [40]:
(<< mat)

#object["[B" 0x4827ce48 "[B@4827ce48"]

it's hard to read what the byte array is, so in clojure we can make a sequence out of it.

In [41]:
(seq (<< mat))

(0 0 0 0 0 0 0 0 0)

let's replace the value in the mat, by using the function *>>*.
*>>* puts values inside the mat using a byte array, here created from a range.

In [42]:
(>> mat (byte-array (range 9)))

#object[org.opencv.core.Mat 0x5a8d0022 "Mat [ 3*3*CV_8UC1, isCont=true, isSubmat=false, nativeObj=0x7fe21ca046e0, dataAddr=0x7fe21ca04740 ]"]

we can check the values again using seq and <<

In [43]:
(seq (<< mat))

(0 1 2 3 4 5 6 7 8)

to multiply the content of the mat, you can use, multiply! and a scalar.

In [44]:
(multiply! mat (new-scalar 2.0))

#object[org.opencv.core.Mat 0x5a8d0022 "Mat [ 3*3*CV_8UC1, isCont=true, isSubmat=false, nativeObj=0x7fe21ca046e0, dataAddr=0x7fe21ca04740 ]"]

we can check the values again using seq and <<, and see that each value of the mat, has been multiplied by 2

In [45]:
(seq (<< mat))

(0 2 4 6 8 10 12 14 16)